# Generated by Django 5.1.7 on 2025-04-06 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidstuff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaidaccount',
            name='plaid_item_id',
        ),
        migrations.RemoveField(
            model_name='plaidaccount',
            name='user_id',
        ),
        migrations.AddField(
            model_name='plaidaccount',
            name='institution',
            field=models.CharField(default='Default set during migrations', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plaidaccount',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
