# Generated by Django 5.2 on 2025-04-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidstuff', '0002_remove_plaidaccount_plaid_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaidaccount',
            name='access_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plaidaccount',
            name='institution',
            field=models.CharField(max_length=255),
        ),
    ]
