# Generated by Django 5.2 on 2025-04-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidstuff', '0003_alter_plaidaccount_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidaccount',
            name='item_id',
            field=models.CharField(default='itemitemitem', max_length=255),
            preserve_default=False,
        ),
    ]
