# Generated by Django 5.2 on 2025-04-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidstuff', '0004_plaidaccount_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidaccount',
            name='connection_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('plaid', 'Plaid')], default='manual', max_length=10),
        ),
    ]
