# Generated by Django 5.2 on 2025-04-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidstuff', '0005_plaidaccount_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidaccount',
            name='connection_data',
            field=models.JSONField(default=dict),
        ),
    ]
